#
# Main Dockerfile for Developing Code
#
# Should create small images < 30MB :)
#
FROM golang:1.9.2-alpine3.6
LABEL maintainer "james.tarball@newtonsystems.co.uk"

# Build Arguments:
# GO_MAIN  - Set the go file to run
# GO_PORT  - The port the go server uses (to make sure it is removed)
# REPO_DIR - The go directory of the repo should be in GOPATH i.e. /go/src/github.com/newtonsystems/<repo>

ARG REPO_DIR
ARG GO_MAIN
ARG GO_PORT

WORKDIR $REPO_DIR

RUN apk add --update --virtual .build-deps \
        swatch \
        bash \
        curl \
        ncurses \
        build-base \
        git \
        musl-dev \
        linux-headers \
        make \
        gcc \
        g++ \
        autoconf \
        automake \
        libtool \
        inotify-tools \
    && rm -rf /var/cache/apk/*

ENV GOPATH /go
ENV PATH $GOPATH/bin:$PATH

COPY ./run.sh /usr/bin/run.sh
RUN chmod +x /usr/bin/run.sh

RUN echo $PWD

ENTRYPOINT ["/usr/bin/run.sh", "--hot-reload", "./server.go", "50000"]
